import { useEffect, useState } from 'react';
import { ArrowDown, ArrowRight, ArrowUpRight, Check, ChevronDown, CookingPot, LayoutGrid, Menu, Monitor, MoveUpRight, QrCode, ReceiptText, Smartphone, Sprout, UtensilsCrossed, Wallet, X } from 'lucide-react';
import { BrandLogo } from '../brand/BrandLogo';
import { ProductPreview } from '../marketing/ProductPreview';
import { loadPlans, planPrice, publicConfig, type BillingPlan } from '../../lib/accountApi';

export interface LandingPageViewProps { onNavigateLogin: () => void; onNavigateRegister: () => void }
const questions = [
  ['What can I explore before signing up?', 'The interactive preview uses sample data. Switch between the overview, kitchen and menu, try a sample ticket, and add dishes to a sample order. It never changes a restaurant’s records or takes a payment.'],
  ['Does it work on a phone?', 'The interface has separate mobile and desktop layouts. Orders, controls and navigation adapt to smaller screens rather than shrinking a desktop page. You can explore the preview on either device.'],
  ['What about KOT and printing?', 'Kitchen tickets put quantities, dishes and instructions first. Print layouts use black ink without decorative banners. You should test your actual printer, paper size and browser before using it during service.'],
  ['Can I subscribe today?', 'Only published, server-configured plans are offered for purchase. If no plan is available, checkout stays closed and no charge is taken. A verified payment—not a browser success screen—must activate a subscription.'],
  ['Is the preview the same as a live restaurant workspace?', 'No. The preview is an isolated demonstration. A live workspace needs verified account access, cloud data, tenant permissions and a configured subscription. We keep those boundaries explicit.'],
];
export function LandingPageView({ onNavigateLogin, onNavigateRegister }: LandingPageViewProps) {
  const [navigationOpen,setNavigationOpen] = useState(false);
  const [plans,setPlans] = useState<BillingPlan[]>([]);
  const [plansLoading,setPlansLoading] = useState(true);
  const [plansError,setPlansError] = useState('');
  const [cycle,setCycle] = useState<'month'|'year'>('month');
  useEffect(() => {
    const controller = new AbortController();
    loadPlans(controller.signal).then(setPlans).catch(() => { if(!controller.signal.aborted) setPlansError('Plan details could not be loaded. Please try again later.'); }).finally(()=>{if(!controller.signal.aborted) setPlansLoading(false);});
    return () => controller.abort();
  },[]);
  useEffect(() => {
    if (!navigationOpen) return;
    const close = (event:KeyboardEvent)=>{if(event.key==='Escape'){setNavigationOpen(false);document.getElementById('site-menu-toggle')?.focus();}};
    window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close);
  },[navigationOpen]);
  const closeNavigation = () => setNavigationOpen(false);
  return <div className="site-root">
    <a className="site-skip" href="#site-main">Skip to content</a>
    <header className="site-header"><div className="site-header-inner"><a href="/" aria-label="Restro8 home" className="site-logo"><BrandLogo/></a><nav aria-label="Main" className={'site-nav '+(navigationOpen?'is-open':'')} id="site-navigation"><a href="#product" onClick={closeNavigation}>Product</a><a href="#workflow" onClick={closeNavigation}>How it works</a><a href="#plans" onClick={closeNavigation}>Plans</a><a href="#questions" onClick={closeNavigation}>Questions</a></nav><div className="site-header-actions"><button type="button" className="site-login-link" onClick={onNavigateLogin}>Sign in<ArrowUpRight size={15}/></button><button type="button" className="site-button site-header-cta" onClick={onNavigateRegister}>Get started<ArrowRight size={15}/></button><button id="site-menu-toggle" className="site-icon-button site-menu-toggle" type="button" aria-label={navigationOpen?'Close navigation':'Open navigation'} aria-expanded={navigationOpen} aria-controls="site-navigation" onClick={()=>setNavigationOpen(!navigationOpen)}>{navigationOpen?<X size={22}/>:<Menu size={22}/>}</button></div></div></header>
    <main id="site-main" tabIndex={-1}>
      <section className="site-hero site-container"><div className="site-hero-copy"><span className="site-eyebrow"><span className="site-small-mark"/>FOR THE PEOPLE BEHIND THE PLATES</span><h1>Less admin.<br/><em>More hospitality.</em></h1><p>A little clarity. A better service. Bring your tables, orders, kitchen and numbers into one thoughtfully simple workspace.</p><div className="site-hero-actions"><button type="button" className="site-button" onClick={onNavigateRegister}>Find your flow<ArrowRight size={18}/></button><a className="site-text-link" href="#product">Take a closer look<ArrowDown size={17}/></a></div><div className="site-hero-reassurance"><span><Check size={14}/>Explore before you commit</span><span><Check size={14}/>Made for your whole team</span></div><div className="site-hero-divider"/><div className="site-hero-note"><span className="site-note-icon"><Sprout size={22}/></span><p>Great hospitality is human.<br/><strong>Your software should feel that way, too.</strong></p></div></div><div className="site-hero-art"><div className="site-art-ring" aria-hidden="true"/><div className="site-mini-ticket"><span><CookingPot size={15}/> FROM ORDER TO KITCHEN</span><strong>Less chasing.<br/>More serving.</strong><i aria-hidden="true"/></div><div className="site-hero-preview"><ProductPreview compact/></div><div className="site-food-note"><img src="/images/menu/steamed-momo.png" alt="Fresh steamed momo with achar" width={116} height={100}/><div><span>MADE WITH CARE</span><strong>Just like your food.</strong></div></div></div></section>
      <div className="site-audience"><div className="site-container"><span>One thoughtful workspace for</span><p><UtensilsCrossed size={17}/>Restaurants</p><p><Sprout size={17}/>Neighbourhood cafés</p><p><CookingPot size={17}/>Busy kitchens</p><p><LayoutGrid size={17}/>Growing teams</p></div></div>
      <section className="site-section site-container" id="product"><div className="site-section-heading"><div><span className="site-eyebrow">A LITTLE LESS FRICTION</span><h2>See the whole service.<br/><em>Not another spreadsheet.</em></h2></div><p>A familiar rhythm, a fresh perspective. Explore how your day comes together—without making a real order.</p></div><div className="site-product-stage"><div className="site-stage-label"><span><i/>INTERACTIVE PRODUCT PREVIEW</span><small>Try the tabs. Make it yours.</small></div><ProductPreview/></div><div className="site-product-caption"><span><Monitor size={16}/>Room to work on desktop.</span><span><Smartphone size={16}/>Ready for the floor on mobile.</span><p>Illustrative sample data · No account needed</p></div></section>
      <section className="site-section site-container" id="workflow"><div className="site-section-heading"><div><span className="site-eyebrow">FROM THE FIRST HELLO TO THE LAST BILL</span><h2>A good service<br/><em>has a natural flow.</em></h2></div><p>No wall of features. Just the right tools, in the order your team needs them.</p></div><div className="site-flow-grid"><article><div className="site-feature-icon"><LayoutGrid size={23}/></div><span className="site-step">01 / WELCOME</span><h3>A place for every guest.</h3><p>Know what’s open, what’s occupied and where the next order belongs.</p><div className="site-small-floor" aria-hidden="true"><span>T01<i>Seated</i></span><span>T02<i>Available</i></span><span>T03<i>Seated</i></span></div></article><article><div className="site-feature-icon"><CookingPot size={23}/></div><span className="site-step">02 / PREPARE</span><h3>Clear tickets. Calm kitchens.</h3><p>Keep the quantities, notes and next action where everyone can see them.</p><div className="site-small-kot"><strong>2× <span>Steamed momo</span></strong><small>Achar on the side. A little detail, remembered.</small><span><Check size={14}/>Ready for the pass</span></div></article><article><div className="site-feature-icon"><ReceiptText size={23}/></div><span className="site-step">03 / WRAP UP</span><h3>Close the bill, not the story.</h3><p>See what was sold, what was collected and what still needs your attention.</p><div className="site-small-bill"><span>Collected <b>Rs. 1,580</b></span><span>Outstanding <b>Rs. 0</b></span><small>Illustrative bill</small></div></article></div></section>
      <section className="site-details-band"><div className="site-container site-details-grid"><div><span className="site-eyebrow">THE SMALL THINGS ARE THE BIG THINGS</span><h2>Thoughtful by design.<br/>Useful by nature.</h2><p>Space to think. Words that make sense. Controls that don’t get in your way.</p></div><div className="site-detail-list"><article><QrCode size={21}/><div><h3>A menu worth sharing</h3><p>Clear dishes, beautiful food imagery and table-specific menu links.</p></div></article><article><Wallet size={21}/><div><h3>Numbers with context</h3><p>Sales, collections and estimates are labelled for what they really are.</p></div></article><article><Smartphone size={21}/><div><h3>Room for your thumb</h3><p>Purpose-built mobile layouts with reachable actions and readable tickets.</p></div></article></div></div></section>
      <section className="site-section site-container" id="plans"><div className="site-section-heading"><div><span className="site-eyebrow">YOUR NEXT CHAPTER</span><h2>A clear beginning.<br/><em>No surprises.</em></h2></div><p>Explore the product first. Published plans will show the actual price, billing period and what’s included.</p></div>{plansLoading ? <p role="status" className="site-plan-empty">Loading plans…</p> : plans.length ? <><div className="site-billing-toggle" role="group" aria-label="Billing period"><button type="button" aria-pressed={cycle==='month'} onClick={()=>setCycle('month')}>Monthly</button><button type="button" aria-pressed={cycle==='year'} onClick={()=>setCycle('year')}>Yearly</button></div><div className="site-plan-grid">{plans.filter(plan=>plan.interval===cycle).map(plan=><article key={plan.id}><span className="site-eyebrow">{plan.name}</span><h3>{planPrice(plan)}<small> / {plan.interval}</small></h3><p>{plan.description}</p><ul>{plan.features.map(feature=><li key={feature}><Check size={15}/>{feature}</li>)}</ul><button type="button" className="site-button" onClick={onNavigateRegister}>Choose {plan.name}<ArrowRight size={16}/></button></article>)}</div>{!plans.some(plan=>plan.interval===cycle)&&<p className="site-plan-empty">No {cycle==='month'?'monthly':'yearly'} plans are currently published.</p>}</> : <div className="site-launch-card"><div className="site-launch-icon"><Sprout size={32}/></div><div><span className="site-eyebrow">BUILT CAREFULLY. LAUNCHING RESPONSIBLY.</span><h3>Your next great service starts here.</h3><p>{plansError || 'Paid plans are not open yet. Explore Restro8 now; checkout will open only when pricing and live billing are configured.'}</p></div><a href="#product" className="site-button">Explore the product<MoveUpRight size={17}/></a></div>}</section>
      <section className="site-section site-container site-faq" id="questions"><div><span className="site-eyebrow">A FEW GOOD QUESTIONS</span><h2>Before we<br/><em>set the table.</em></h2>{publicConfig.contactEmail&&<a className="site-text-link" href={'mailto:'+publicConfig.contactEmail}>Talk to the team<ArrowUpRight size={16}/></a>}</div><div>{questions.map(([question,answer])=><details key={question}><summary>{question}<ChevronDown size={18}/></summary><p>{answer}</p></details>)}</div></section>
      <section className="site-final-cta site-container"><span className="site-eyebrow">MORE TIME FOR WHAT MATTERS</span><h2>You bring the hospitality.<br/><em>We’ll bring a little clarity.</em></h2><button type="button" className="site-button site-button-light" onClick={onNavigateRegister}>Get to know Restro8<ArrowRight size={17}/></button><span className="site-final-infinity" aria-hidden="true">∞</span></section>
    </main><footer className="site-footer site-container"><div><a href="/" aria-label="Restro8 home"><BrandLogo/></a><p>Infinite hospitality.<br/>Thoughtfully simple restaurant software.</p></div><nav aria-label="Footer"><a href="#product">Product</a><a href="#plans">Plans</a><button type="button" onClick={onNavigateLogin}>Sign in</button>{publicConfig.privacyUrl&&<a href={publicConfig.privacyUrl}>Privacy</a>}{publicConfig.termsUrl&&<a href={publicConfig.termsUrl}>Terms</a>}</nav><div className="site-footer-bottom"><span>© {new Date().getFullYear()} Restro8</span><span>Made for the people behind the plates.</span></div></footer>
  </div>;
}
