import { useState } from 'react';
import { ArrowRight, Check, ChevronDown, CookingPot, LayoutDashboard, Plus, Search, UtensilsCrossed } from 'lucide-react';
import { BrandLogo } from '../brand/BrandLogo';
const revenue = [18, 26, 21, 38, 32, 46, 42, 59, 50, 68, 61, 77];
const dishes = [
  {name:'Steamed momo',category:'House favourites',price:280,image:'/images/menu/steamed-momo.png'},
  {name:'Thakali khana',category:'From our kitchen',price:680,image:'/images/menu/thakali-mutton.png'},
  {name:'Jhol momo',category:'A little comfort',price:330,image:'/images/menu/jhol-momo.png'},
];
export function ProductPreview({ compact = false }: { compact?: boolean }) {
  const [tab,setTab] = useState<'overview' | 'kitchen' | 'menu'>('overview');
  const [ready,setReady] = useState(false);
  const [quantities,setQuantities] = useState([0,0,0]);
  const subtotal = quantities.reduce((sum,quantity,index) => sum + quantity * dishes[index].price,0);
  return <div className={'site-preview ' + (compact ? 'is-compact' : '')}>
    <div className="preview-chrome"><span className="preview-dots" aria-hidden="true"><i/><i/><i/></span><span>YOUR NEXT GREAT SERVICE</span><span className="preview-sample">Sample data</span></div>
    <div className="preview-shell"><aside className="preview-sidebar" aria-hidden="true"><BrandLogo compact/><span className={tab === 'overview' ? 'is-active' : ''}><LayoutDashboard size={17}/></span><span className={tab === 'kitchen' ? 'is-active' : ''}><CookingPot size={17}/></span><span className={tab === 'menu' ? 'is-active' : ''}><UtensilsCrossed size={17}/></span><span className="preview-avatar">YK</span></aside>
      <div className="preview-main"><div className="preview-top"><span><i/>Your kitchen <ChevronDown size={12}/></span><Search size={16} aria-hidden="true"/></div>
        <div className="preview-switcher" role="group" aria-label="Explore the product preview">{(['overview','kitchen','menu'] as const).map(value => <button type="button" key={value} aria-pressed={tab===value} onClick={() => setTab(value)}>{value === 'overview' ? 'Overview' : value === 'kitchen' ? 'Kitchen' : 'Menu & orders'}</button>)}</div>
        {tab === 'overview' && <div className="preview-content preview-enter"><div className="preview-heading"><div><p>THE BIG PICTURE</p><h3>A good day, in the making.</h3></div><span className="preview-date">Today <ChevronDown size={11}/></span></div>
          <div className="preview-metrics"><div className="is-featured"><span>Collected</span><strong>Rs. 24,850</strong><small>Today’s sample sales</small></div><div><span>Orders</span><strong>42</strong><small>6 in preparation</small></div><div><span>Tables</span><strong>8 <em>/ 12</em></strong><small>4 ready to welcome</small></div></div>
          <div className="preview-detail-grid"><section className="preview-revenue"><div><strong>A steady service</strong><span>Sales · NPR</span></div><div className="preview-bars" role="img" aria-label="Illustrative sample sales chart increasing through the day">{revenue.map((height,index) => <i key={index} style={{height:height+'%'}}/>)}</div><div className="preview-axis"><span>10:00</span><span>14:00</span><span>18:00</span><span>22:00</span></div></section><section className="preview-floor"><strong>A place for everyone</strong><div>{Array.from({length:6},(_,index) => <span key={index} className={index%3===1 ? 'is-empty':''}>T{String(index+1).padStart(2,'0')}</span>)}</div><small><i/>Available <b/>Occupied</small></section></div>
          <div className="preview-order"><span className="preview-order-icon"><CookingPot size={18}/></span><div><strong>Table 04 · Dinner for two</strong><small>2 momo · 1 thakali · 2 chiya</small></div><span className="preview-status">Preparing</span></div>
        </div>}
        {tab === 'kitchen' && <div className="preview-content preview-enter"><div className="preview-heading"><div><p>KEEP SERVICE MOVING</p><h3>A calmer kitchen.</h3></div><span className="preview-date">2 tickets</span></div><div className="preview-tickets"><article><span className="preview-ticket-number">#104 · {ready ? 'READY' : 'PREPARING'}</span><h4>Garden table 4</h4><p>5 min · Main kitchen</p><div className="preview-ticket-line"><b>2×</b><span>Steamed momo<small>Achar on the side</small></span></div><div className="preview-ticket-line"><b>1×</b><span>Thakali khana</span></div><button type="button" onClick={() => setReady(!ready)}>{ready ? <Check size={16}/> : <CookingPot size={16}/>} {ready ? 'Ready · reset preview' : 'Send to the pass'}</button></article><article><span className="preview-ticket-number">#105 · WAITING</span><h4>Window table 2</h4><p>2 min · Coffee station</p><div className="preview-ticket-line"><b>2×</b><span>Masala chiya<small>Less sugar, please</small></span></div><span className="preview-note">The details that make service personal.</span></article></div><p className="preview-feedback" role="status">{ready ? 'Sample ticket ready. Your team knows what happens next.' : 'Try sending the sample ticket to the pass.'}</p></div>}
        {tab === 'menu' && <div className="preview-content preview-enter"><div className="preview-heading"><div><p>MADE WITH CARE</p><h3>Good food. Clear choices.</h3></div></div><div className="preview-dishes">{dishes.map((dish,index) => <article key={dish.name}><img src={dish.image} alt={dish.name} width={160} height={130} loading="lazy"/><small>{dish.category}</small><h4>{dish.name}</h4><div><strong>Rs. {dish.price}</strong><button type="button" aria-label={'Add '+dish.name+' to sample order'} onClick={() => setQuantities(values => values.map((value,i)=>i===index?value+1:value))}>{quantities[index] ? quantities[index] : <Plus size={17}/>}</button></div></article>)}</div><div className="preview-basket" role="status"><span>{quantities.reduce((a,b)=>a+b,0)} items · Sample subtotal</span><strong>Rs. {subtotal.toLocaleString('en-NP')}</strong><button type="button" onClick={()=>setQuantities([0,0,0])}>Reset</button></div><p className="preview-feedback">Explore freely. No real orders or payments are created.</p></div>}
      </div>
    </div><div className="preview-bottom"><span><i/>A preview of your daily rhythm</span><span>Made for hospitality <ArrowRight size={12}/></span></div>
  </div>;
}
